### ISSUE TITLE
Some problems for the code

### ISSUE THREAD

**Issue by wzfhaha** [acbull/LADIES#2]
Hi, bro,
   Thanks for making the code public. But there are so many bugs in the code which can't be run directly. By the way, could you please report the detailed parameters you used for results in Table 3 on the four datasets ? I tuned a lot but can't reproduce the performance. Thanks very much!

**Comment by acbull** [comment]
Hi:

Sorry for the trouble. The previous version of code indeed contains many typo bugs. Sorry about that.

I've fixed all the mentioned typos, and you can try the current version. For the hyperparameters, it's exactly the default ones in my argument lists. The only one that need to enumerate is the samp_num

You can try:
python3 pytorch_ladies.py --cuda 0 --dataset pubmed --sample_method ladies --samp_num 512
to see the results.
