### ISSUE TITLE
fastgcn_sampler

### ISSUE THREAD

**Issue by SongFGH** [acbull/LADIES#7]
Hi, bro,
in your code,

fastgcn_sampler:
adj = row_norm(U[: , after_nodes].multiply(1/p[after_nodes]))

However, other people say: we should row - select and col - select the lap_matrix (U).
More details can see: https://github.com/khanhhhh/ladies/blob/khanh/solution_random_block/sampler.py

I can not understand, can you explain more?

**Comment by acbull** [comment]
This is just for different implementation. In line 140 we do the row-select on the Laplacian matrix, and then compute its square for calculating probability. Their implementation pre-compute a U2 (square of Laplacian matrix), so they will re-do the row-select again on Laplacian matrix again.

**Comment by SongFGH** [comment]
Thanks
